#!/usr/bin/env python3
"""
OVPN Config Forge – Web Panel
ShadowCat Edition – generate, download, and monitor OVPN profiles
"""
import os
import sys
import subprocess
import shutil
import json
import time
import zipfile
from pathlib import Path
from datetime import datetime

# ===== AUTO‑INSTALL FLASK VIA APT =====
try:
    from flask import Flask, render_template_string, request, send_file, jsonify, redirect, url_for
    from werkzeug.utils import secure_filename
except ImportError:
    print("🐱 Flask not found. Installing via apt...", file=sys.stderr)
    subprocess.check_call(["apt-get", "update"], stderr=subprocess.DEVNULL)
    subprocess.check_call(["apt-get", "install", "-y", "python3-flask", "python3-werkzeug"])
    from flask import Flask, render_template_string, request, send_file, jsonify, redirect, url_for
    from werkzeug.utils import secure_filename

# ========== CONFIGURATION ==========
BASE_DIR = Path("/opt/ovpn_forge")
CONFIG_DIR = BASE_DIR / "configs"        # generated .ovpn files
UPLOAD_DIR = BASE_DIR / "uploads"        # temporary for certs
PID_DIR = Path("/var/run/ovpn_manager")  # reuse for status checking (optional)
LOG_DIR = Path("/var/log/ovpn_manager")

for d in [BASE_DIR, CONFIG_DIR, UPLOAD_DIR, PID_DIR, LOG_DIR]:
    d.mkdir(parents=True, exist_ok=True)

HOST = "0.0.0.0"
PORT = 5000

# ========== TEMPLATE ==========
TEMPLATE = """# OpenVPN Client Config – {name}
# Generated by ShadowCat on {date}

client
dev tun
proto {proto}
remote {server} {port}
resolv-retry infinite
nobind
persist-key
persist-tun
remote-cert-tls server
cipher {cipher}
auth {auth}
comp-lzo {comp}
verb 3

<ca>
{ca_cert}
</ca>
<cert>
{client_cert}
</cert>
<key>
{client_key}
</key>
"""

# ========== FLASK APP ==========
app = Flask(__name__)
app.config['UPLOAD_FOLDER'] = str(UPLOAD_DIR)
app.config['MAX_CONTENT_LENGTH'] = 16 * 1024 * 1024

# ---------------- Helper Functions ----------------
def get_active_connections():
    """Return dict of active OpenVPN processes (name -> pid)"""
    active = {}
    for pid_file in PID_DIR.glob("*.pid"):
        try:
            pid = int(pid_file.read_text().strip())
            if os.kill(pid, 0) == 0:
                active[pid_file.stem] = pid
        except (ProcessLookupError, ValueError, OSError):
            pass
    return active

def get_generated_profiles():
    """Return list of dicts with info about each .ovpn file"""
    profiles = []
    for ovpn_file in CONFIG_DIR.glob("*.ovpn"):
        name = ovpn_file.stem
        # Try to extract metadata from file header
        meta = {"name": name, "file": str(ovpn_file), "size": ovpn_file.stat().st_size}
        with open(ovpn_file) as f:
            content = f.read()
            # Quick parse: look for proto, remote lines
            for line in content.splitlines():
                if line.startswith("proto "):
                    meta["proto"] = line.split()[1]
                elif line.startswith("remote "):
                    parts = line.split()
                    if len(parts) >= 3:
                        meta["server"] = parts[1]
                        meta["port"] = parts[2]
        # Defaults if not found
        meta.setdefault("proto", "unknown")
        meta.setdefault("server", "unknown")
        meta.setdefault("port", "unknown")
        meta["active"] = name in get_active_connections()
        meta["created"] = datetime.fromtimestamp(ovpn_file.stat().st_ctime).strftime("%Y-%m-%d %H:%M")
        profiles.append(meta)
    return profiles

def generate_config(server, port, proto, name, ca_cert, client_cert, client_key,
                    cipher="AES-256-CBC", auth="SHA256", comp="yes"):
    """Write a .ovpn file to CONFIG_DIR and return its path"""
    config = TEMPLATE.format(
        name=name,
        server=server,
        port=port,
        proto=proto,
        cipher=cipher,
        auth=auth,
        comp=comp,
        date=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        ca_cert=ca_cert.strip() if ca_cert else "PASTE YOUR CA CERT HERE",
        client_cert=client_cert.strip() if client_cert else "PASTE YOUR CLIENT CERT HERE",
        client_key=client_key.strip() if client_key else "PASTE YOUR CLIENT KEY HERE"
    )
    out_file = CONFIG_DIR / f"{name}.ovpn"
    with open(out_file, "w") as f:
        f.write(config)
    return out_file

# ---------------- Routes ----------------
@app.route('/')
def index():
    profiles = get_generated_profiles()
    return render_template_string(HTML, profiles=profiles)

@app.route('/generate', methods=['POST'])
def generate():
    # Get form data
    server = request.form.get('server', '').strip()
    protocols = request.form.getlist('protocols')  # list
    ports_raw = request.form.get('ports', '1194,443').strip()
    cipher = request.form.get('cipher', 'AES-256-CBC')
    auth = request.form.get('auth', 'SHA256')
    comp = request.form.get('comp', 'yes')
    ca_file = request.files.get('ca')
    cert_file = request.files.get('cert')
    key_file = request.files.get('key')

    # Read certificates if uploaded
    ca_cert = client_cert = client_key = ""
    if ca_file and ca_file.filename:
        ca_cert = ca_file.read().decode('utf-8')
    if cert_file and cert_file.filename:
        client_cert = cert_file.read().decode('utf-8')
    if key_file and key_file.filename:
        client_key = key_file.read().decode('utf-8')

    # Parse ports
    ports = [p.strip() for p in ports_raw.split(',') if p.strip().isdigit()]
    if not ports:
        ports = ["1194"]

    # Generate for each combo
    generated = []
    for proto in protocols:
        for port in ports:
            name = f"client_{proto}_{port}"
            out_path = generate_config(
                server=server,
                port=port,
                proto=proto,
                name=name,
                ca_cert=ca_cert,
                client_cert=client_cert,
                client_key=client_key,
                cipher=cipher,
                auth=auth,
                comp=comp
            )
            generated.append(str(out_path))

    return redirect(url_for('index'))

@app.route('/download/<name>')
def download(name):
    file_path = CONFIG_DIR / f"{name}.ovpn"
    if not file_path.exists():
        return "File not found", 404
    return send_file(file_path, as_attachment=True)

@app.route('/download_all')
def download_all():
    # Create a zip with all configs
    zip_path = BASE_DIR / "all_configs.zip"
    with zipfile.ZipFile(zip_path, 'w') as zipf:
        for ovpn in CONFIG_DIR.glob("*.ovpn"):
            zipf.write(ovpn, ovpn.name)
    return send_file(zip_path, as_attachment=True, download_name="ovpn_configs.zip")

@app.route('/delete/<name>', methods=['POST'])
def delete(name):
    file_path = CONFIG_DIR / f"{name}.ovpn"
    if file_path.exists():
        file_path.unlink()
    return redirect(url_for('index'))

# ---------------- HTML Template ----------------
HTML = """
<!DOCTYPE html>
<html>
<head>
    <title>🐱 OVPN Config Forge</title>
    <style>
        body { font-family: 'Courier New', monospace; background: #0a0a0a; color: #0f0; padding: 20px; }
        .container { max-width: 1200px; margin: auto; }
        h1 { color: #0f0; border-bottom: 2px solid #0f0; padding-bottom: 10px; }
        .card { background: #1a1a1a; padding: 15px; margin: 15px 0; border: 1px solid #0f0; border-radius: 5px; }
        .row { display: flex; gap: 20px; flex-wrap: wrap; }
        .col { flex: 1; min-width: 300px; }
        .btn { background: #0f0; color: #000; border: none; padding: 8px 16px; cursor: pointer; font-weight: bold; }
        .btn:hover { background: #0a0; }
        .btn-danger { background: #f00; color: #fff; }
        .btn-danger:hover { background: #c00; }
        input, select, textarea { background: #222; color: #0f0; border: 1px solid #0f0; padding: 5px; width: 100%; }
        .status { color: #ff0; }
        .status.active { color: #0f0; }
        .status.inactive { color: #f00; }
        .file-list { list-style: none; padding: 0; }
        .file-list li { padding: 8px; border-bottom: 1px solid #333; display: flex; justify-content: space-between; align-items: center; flex-wrap: wrap; }
        .file-info { font-size: 0.8em; color: #aaa; }
        .actions { display: flex; gap: 8px; flex-wrap: wrap; }
        .footer { margin-top: 30px; color: #666; font-size: 0.8em; }
    </style>
</head>
<body>
<div class="container">
    <h1>🐱 OVPN Config Forge – Shadow</h1>
    <div class="row">
        <div class="col">
            <div class="card">
                <h2>⚙️ Generate New Configs</h2>
                <form method="post" action="/generate" enctype="multipart/form-data">
                    <label>Server IP / Hostname</label>
                    <input type="text" name="server" placeholder="vpn.example.com" required>

                    <label>Protocols</label>
                    <label><input type="checkbox" name="protocols" value="udp" checked> UDP</label>
                    <label><input type="checkbox" name="protocols" value="tcp" checked> TCP</label>

                    <label>Ports (comma-separated)</label>
                    <input type="text" name="ports" value="1194,443" placeholder="1194,443,8080">

                    <label>Cipher</label>
                    <select name="cipher">
                        <option value="AES-256-CBC">AES-256-CBC</option>
                        <option value="AES-256-GCM">AES-256-GCM</option>
                        <option value="BF-CBC">BF-CBC</option>
                    </select>

                    <label>Auth</label>
                    <select name="auth">
                        <option value="SHA256">SHA256</option>
                        <option value="SHA512">SHA512</option>
                        <option value="SHA1">SHA1</option>
                    </select>

                    <label>Compression</label>
                    <select name="comp">
                        <option value="yes">yes</option>
                        <option value="no">no</option>
                        <option value="lzo">lzo</option>
                    </select>

                    <label>Upload CA Certificate (optional)</label>
                    <input type="file" name="ca" accept=".crt,.pem,.txt">

                    <label>Upload Client Certificate (optional)</label>
                    <input type="file" name="cert" accept=".crt,.pem,.txt">

                    <label>Upload Client Key (optional)</label>
                    <input type="file" name="key" accept=".key,.pem,.txt">

                    <button class="btn" type="submit">🚀 Generate</button>
                </form>
            </div>
        </div>
        <div class="col">
            <div class="card">
                <h2>📋 Generated Profiles <span style="font-size:0.7em;">({{ profiles|length }})</span></h2>
                <div style="margin-bottom:10px;">
                    <a href="/download_all" class="btn">⬇ Download All (ZIP)</a>
                </div>
                <ul class="file-list">
                    {% for p in profiles %}
                    <li>
                        <span>
                            <strong>{{ p.name }}</strong><br>
                            <span class="file-info">
                                {{ p.server }}:{{ p.port }} ({{ p.proto }}) – {{ p.created }} – {{ p.size }} bytes
                            </span>
                            <span class="status {% if p.active %}active{% else %}inactive{% endif %}">
                                ● {% if p.active %}ACTIVE{% else %}INACTIVE{% endif %}
                            </span>
                        </span>
                        <div class="actions">
                            <a href="/download/{{ p.name }}" class="btn">⬇</a>
                            <form method="post" action="/delete/{{ p.name }}" style="display:inline;">
                                <button class="btn btn-danger" onclick="return confirm('Delete?')">🗑</button>
                            </form>
                        </div>
                    </li>
                    {% else %}
                    <li>No configs generated yet.</li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
    <div class="footer">🐱 ShadowCat – root@universe | uptime ∞</div>
</div>
</body>
</html>
"""

# ========== MAIN ==========
if __name__ == "__main__":
    # Ensure we have OpenVPN for status check (optional)
    if not shutil.which("openvpn"):
        print("⚠️ OpenVPN not installed – status checks will not work.", file=sys.stderr)
        print("   Install: sudo apt install openvpn", file=sys.stderr)
    print(f"🐱 OVPN Config Forge running on http://{HOST}:{PORT}")
    app.run(host=HOST, port=PORT, debug=False, threaded=True)
